# Generated by Django 3.2.9 on 2022-09-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hno', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationsName', models.CharField(max_length=30)),
                ('fromDate', models.CharField(max_length=30)),
                ('toDate', models.CharField(max_length=30)),
                ('percentage', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('fromDate', models.CharField(max_length=30)),
                ('toDate', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('phoneNo', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='upload/images/')),
                ('addressDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.addressdetails')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.projects')),
                ('qualifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.qualifications')),
                ('workExperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workexperience')),
            ],
        ),
    ]
